train:
  learning_rate: 0.0002
  beta_1: 0.5
  beta_2: 0.999
  save_dir_img: "./result/saved_img"
  save_dir_model: "./result/weights/saved_model"
  log_period: 500   # 학습 로그 출력 주기
  save_period: 2000   # 모델 가중치 저장 주기
  lambda_1: 10  # gradient penalty 중요도
  lambda_2: 10  # 재구성 오차 중요도
  saved_step: 0   # 학습 재개 스텝수
  max_step: 8000  # 최대 학습 스텝수
  iter_g: 2   # 1 iter 내 각 모델의 갱신 횟수
  iter_d: 1
  iter_cd: 1

dataset:
  batch_size: 4
  num_workers: 4
  train_path: "../../data/ixi_dataset/*.nii.gz"

model:
  latant_dim: 1000

plot:
  cube_len: 64